
var game_file_list = [
    //以下为自动修改，请勿修改
    //----auto game_file_list start----
	"libs/modules/egret/egret.js",
	"libs/modules/egret/egret.native.js",
	"libs/modules/game/game.js",
	"libs/modules/tween/tween.js",
	"libs/modules/res/res.js",
	"libs/modules/socket/socket.js",
	"libs/modules/particle/particle.js",
	"polyfill/promise.js",
	"bin-debug/AH_MJ/src/Main.js",
	"bin-debug/AH_CP/Main.js",
	"bin-debug/AH_MJ/src/model/baseModel.js",
	"bin-debug/AH_MJ/src/model/dataModel/userBaseModel.js",
	"bin-debug/AH_MJ/src/view/baseView.js",
	"bin-debug/AH_CP/model/dataModel/userBaseModel.js",
	"bin-debug/AH_MJ/src/scene/baseScene.js",
	"bin-debug/AH_MJ/src/view/module/button.js",
	"bin-debug/AH_MJ/src/model/dataModel/userModel.js",
	"bin-debug/AH_MJ/src/view/scene/game/card/cardView.js",
	"bin-debug/AH_MJ/src/view/scene/game/card/userCardView.js",
	"bin-debug/AH_CP/view/scene/game/card/userCardView.js",
	"bin-debug/AH_MJ/src/scene/game/baseScene.js",
	"bin-debug/AH_CP/view/scene/game/card/cardView.js",
	"bin-debug/AH_MJ/src/model/serviceModel/baseService.js",
	"bin-debug/AH_MJ/src/view/module/doubleBtn.js",
	"bin-debug/AH_MJ/src/view/module/sound/soundBtn.js",
	"bin-debug/AH_MJ/src/view/popup/popupBaseView.js",
	"bin-debug/AH_CP/model/dataModel/userModel.js",
	"bin-debug/AH_CP/model/baseModel.js",
	"bin-debug/AH_MJ/src/view/scene/hall/userInfo.js",
	"bin-debug/AH_MJ/src/view/scene/game/card/user4Cardsview.js",
	"bin-debug/AH_MJ/src/view/scene/game/card/user3Cardsview.js",
	"bin-debug/AH_MJ/src/view/scene/game/card/user2Cardsview.js",
	"bin-debug/AH_MJ/src/view/scene/game/card/user1Cardsview.js",
	"bin-debug/AH_MJ/src/view/scene/game/card/stopCardView.js",
	"bin-debug/AH_MJ/src/view/scene/game/card/cpgCardView.js",
	"bin-debug/AH_MJ/src/view/scene/game/card/chiCardGroupView.js",
	"bin-debug/AH_MJ/src/view/scene/hall/notice.js",
	"bin-debug/AH_MJ/src/view/scene/game/backgroundView.js",
	"bin-debug/AH_MJ/src/view/scene/game/backgroundUpView.js",
	"bin-debug/AH_MJ/src/view/popup/userinfoView.js",
	"bin-debug/AH_MJ/src/view/popup/userAgreementView.js",
	"bin-debug/AH_MJ/src/view/popup/tipView.js",
	"bin-debug/AH_MJ/src/view/popup/smallSettlementView.js",
	"bin-debug/AH_MJ/src/view/popup/shareView.js",
	"bin-debug/AH_MJ/src/view/popup/setView.js",
	"bin-debug/AH_MJ/src/view/popup/selectBox.js",
	"bin-debug/AH_MJ/src/view/popup/replaceCreateRoomView.js",
	"bin-debug/AH_MJ/src/view/popup/radioAreaView.js",
	"bin-debug/AH_MJ/src/view/scene/hall/joinRoom.js",
	"bin-debug/AH_MJ/src/view/popup/newsView.js",
	"bin-debug/AH_MJ/src/view/popup/maxSettlementView.js",
	"bin-debug/AH_MJ/src/view/popup/joinRoomViwe.js",
	"bin-debug/AH_MJ/src/view/popup/hitView.js",
	"bin-debug/AH_MJ/src/view/popup/helpView.js",
	"bin-debug/AH_MJ/src/view/popup/feedbackView.js",
	"bin-debug/AH_MJ/src/view/popup/dissolveRoomView.js",
	"bin-debug/AH_MJ/src/view/popup/createRoomview.js",
	"bin-debug/AH_MJ/src/view/popup/chatView.js",
	"bin-debug/AH_MJ/src/view/popup/achievementView.js",
	"bin-debug/AH_MJ/src/view/module/user/userView.js",
	"bin-debug/AH_MJ/src/view/module/user/infoView.js",
	"bin-debug/AH_MJ/src/view/module/user/headView.js",
	"bin-debug/AH_MJ/src/view/module/user/headCircleView.js",
	"bin-debug/AH_MJ/src/view/scene/hall/createRoom.js",
	"bin-debug/AH_MJ/src/view/module/sound/effectSoundBtn.js",
	"bin-debug/AH_MJ/src/view/scene/hall/btnGroop.js",
	"bin-debug/AH_MJ/src/view/module/joinRoomNumBtn.js",
	"bin-debug/AH_MJ/src/view/scene/game/waitBtnView.js",
	"bin-debug/AH_MJ/src/view/scene/layer/LoadingUI.js",
	"bin-debug/AH_MJ/src/view/scene/game/smallSettleInfoView.js",
	"bin-debug/AH_MJ/src/scene/layer/popup.js",
	"bin-debug/AH_MJ/src/scene/layer/loading.js",
	"bin-debug/AH_MJ/src/scene/hallScene.js",
	"bin-debug/AH_MJ/src/view/scene/layer/loadingData.js",
	"bin-debug/AH_MJ/src/scene/gameScene.js",
	"bin-debug/AH_MJ/src/scene/game/waitScene.js",
	"bin-debug/AH_MJ/src/scene/game/prepareScene.js",
	"bin-debug/AH_MJ/src/scene/game/playingScene.js",
	"bin-debug/AH_MJ/src/view/scene/game/settleInfoView.js",
	"bin-debug/AH_MJ/src/view/scene/game/recordView.js",
	"bin-debug/AH_MJ/src/model/serviceModel/weixinJSSDKService.js",
	"bin-debug/AH_MJ/src/model/serviceModel/webSocketService.js",
	"bin-debug/AH_MJ/src/view/scene/game/playingAniView.js",
	"bin-debug/AH_MJ/src/model/managerModel.js",
	"bin-debug/AH_MJ/src/model/hallModel.js",
	"bin-debug/AH_MJ/src/model/gameModel/playeringModel.js",
	"bin-debug/AH_MJ/src/model/gameModel/BackLayerModel.js",
	"bin-debug/AH_MJ/src/model/gameModel.js",
	"bin-debug/AH_MJ/src/view/scene/game/maxSettleInfoView.js",
	"bin-debug/AH_MJ/src/model/dataModel/UserGroupModel.js",
	"bin-debug/AH_MJ/src/view/scene/game/cpghBtnView.js",
	"bin-debug/AH_MJ/src/view/scene/game/cpghBtn.js",
	"bin-debug/AH_MJ/src/view/scene/game/clockView.js",
	"bin-debug/AH_MJ/src/model/dataModel/cardModel.js",
	"bin-debug/AH_MJ/src/model/dataModel/console.js",
	"bin-debug/AH_MJ/src/model/dataModel/cpgCardModel.js",
	"bin-debug/AH_MJ/src/view/scene/game/chatAniView.js",
	"bin-debug/AH_MJ/src/model/dataModel/killRoomModel.js",
	"bin-debug/AH_MJ/src/model/dataModel/roomInfoModel.js",
	"bin-debug/AH_MJ/src/model/dataModel/smallSettleModel.js",
	"bin-debug/AH_MJ/src/model/dataModel/urlDataModel.js",
	"bin-debug/AH_MJ/src/model/dataModel/cpghBtnModel.js",
	"bin-debug/AH_MJ/src/model/dataModel/testDataModel.js",
	"bin-debug/AH_CP/view/scene/layer/loadingData.js",
	"bin-debug/AH_CP/view/scene/hall/userInfo.js",
	"bin-debug/AH_CP/view/scene/hall/notice.js",
	"bin-debug/AH_CP/view/scene/hall/joinRoom.js",
	"bin-debug/AH_CP/view/scene/hall/createRoom.js",
	"bin-debug/AH_CP/view/scene/hall/btnGroop.js",
	"bin-debug/AH_MJ/src/model/hallModel/repalceRoomModel.js",
	"bin-debug/AH_CP/view/scene/game/waitBtnView.js",
	"bin-debug/AH_CP/view/scene/game/smallSettleInfoView.js",
	"bin-debug/AH_MJ/src/model/serviceModel/httpService.js",
	"bin-debug/AH_MJ/src/model/serviceModel/statisticService.js",
	"bin-debug/AH_CP/view/scene/game/settleInfoView.js",
	"bin-debug/AH_CP/view/scene/game/recordView.js",
	"bin-debug/AH_MJ/src/model/soundModel.js",
	"bin-debug/AH_CP/view/scene/game/playingAniView.js",
	"bin-debug/AH_CP/view/scene/game/maxSettleInfoView.js",
	"bin-debug/AH_CP/view/scene/game/cpghBtnView.js",
	"bin-debug/AH_CP/view/scene/game/cpghBtn.js",
	"bin-debug/AH_CP/view/scene/game/clockView.js",
	"bin-debug/AH_CP/view/scene/game/chatAniView.js",
	"bin-debug/AH_CP/view/scene/game/card/user4Cardsview.js",
	"bin-debug/AH_CP/view/scene/game/card/user3Cardsview.js",
	"bin-debug/AH_CP/view/scene/game/card/user2Cardsview.js",
	"bin-debug/AH_CP/view/scene/game/card/user1Cardsview.js",
	"bin-debug/AH_CP/view/scene/game/card/stopCardView.js",
	"bin-debug/AH_CP/view/scene/game/card/cpgCardView.js",
	"bin-debug/AH_CP/view/scene/game/card/chiCardGroupView.js",
	"bin-debug/AH_MJ/src/view/module/sound/bgSoundBtn.js",
	"bin-debug/AH_CP/view/scene/game/backgroundView.js",
	"bin-debug/AH_CP/view/scene/game/backgroundUpView.js",
	"bin-debug/AH_CP/view/popup/userinfoView.js",
	"bin-debug/AH_CP/view/popup/userAgreementView.js",
	"bin-debug/AH_CP/view/popup/tipView.js",
	"bin-debug/AH_CP/view/popup/smallSettlementView.js",
	"bin-debug/AH_CP/view/popup/shareView.js",
	"bin-debug/AH_CP/view/popup/setView.js",
	"bin-debug/AH_CP/view/popup/selectBox.js",
	"bin-debug/AH_CP/view/popup/replaceCreateRoomView.js",
	"bin-debug/AH_CP/view/popup/radioAreaView.js",
	"bin-debug/AH_CP/view/popup/newsView.js",
	"bin-debug/AH_CP/view/scene/layer/LoadingUI.js",
	"bin-debug/AH_CP/view/popup/joinRoomViwe.js",
	"bin-debug/AH_CP/view/popup/hitView.js",
	"bin-debug/AH_CP/view/popup/helpView.js",
	"bin-debug/AH_CP/view/popup/feedbackView.js",
	"bin-debug/AH_CP/view/popup/dissolveRoomView.js",
	"bin-debug/AH_CP/view/popup/createRoomview.js",
	"bin-debug/AH_CP/view/popup/chatView.js",
	"bin-debug/AH_CP/view/popup/achievementView.js",
	"bin-debug/AH_CP/view/module/user/userView.js",
	"bin-debug/AH_CP/view/module/user/infoView.js",
	"bin-debug/AH_CP/view/module/user/headView.js",
	"bin-debug/AH_CP/view/module/user/headCircleView.js",
	"bin-debug/AH_CP/view/module/sound/effectSoundBtn.js",
	"bin-debug/AH_CP/view/module/joinRoomNumBtn.js",
	"bin-debug/AH_CP/view/module/doubleBtn.js",
	"bin-debug/AH_CP/scene/layer/popup.js",
	"bin-debug/AH_CP/scene/layer/loading.js",
	"bin-debug/AH_CP/scene/layer/console.js",
	"bin-debug/AH_CP/scene/hallScene.js",
	"bin-debug/AH_CP/scene/gameScene.js",
	"bin-debug/AH_CP/scene/game/waitScene.js",
	"bin-debug/AH_CP/scene/game/prepareScene.js",
	"bin-debug/AH_CP/scene/game/playingScene.js",
	"bin-debug/AH_CP/scene/game/baseScene.js",
	"bin-debug/AH_CP/model/serviceModel/weixinJSSDKService.js",
	"bin-debug/AH_CP/model/serviceModel/webSocketService.js",
	"bin-debug/AH_CP/model/managerModel.js",
	"bin-debug/AH_CP/model/hallModel/repalceRoomModel.js",
	"bin-debug/AH_CP/model/hallModel.js",
	"bin-debug/AH_CP/model/gameModel/playeringModel.js",
	"bin-debug/AH_CP/model/gameModel/BackLayerModel.js",
	"bin-debug/AH_CP/model/gameModel.js",
	"bin-debug/AH_CP/model/dataModel/UserGroupModel.js",
	"bin-debug/AH_CP/model/dataModel/urlDataModel.js",
	"bin-debug/AH_CP/model/dataModel/smallSettleModel.js",
	"bin-debug/AH_CP/model/dataModel/roomInfoModel.js",
	"bin-debug/AH_CP/model/dataModel/killRoomModel.js",
	"bin-debug/AH_CP/model/dataModel/cpghBtnModel.js",
	"bin-debug/AH_CP/model/dataModel/cpgCardModel.js",
	"bin-debug/AH_CP/model/dataModel/cardModel.js",
	"bin-debug/AH_CP/view/popup/maxSettlementView.js",
	//----auto game_file_list end----
];

var window = this;

egret_native.setSearchPaths([""]);

egret_native.requireFiles = function () {
    for (var key in game_file_list) {
        var src = game_file_list[key];
        require(src);
    }
};

egret_native.egretInit = function () {
    if(egret_native.featureEnable) {
        //控制一些优化方案是否开启
        var result = egret_native.featureEnable({
            
        });
    }
    egret_native.requireFiles();
    //egret.dom为空实现
    egret.dom = {};
    egret.dom.drawAsCanvas = function () {
    };
};

egret_native.egretStart = function () {
    var option = {
        //以下为自动修改，请勿修改
        //----auto option start----
		entryClassName: "Main",
		frameRate: 30,
		scaleMode: "showAll",
		contentWidth: 1136,
		contentHeight: 720,
		showPaintRect: false,
		showFPS: false,
		fpsStyles: "x:0,y:0,size:12,textColor:0xffffff,bgAlpha:0.9",
		showLog: false,
		logFilter: "",
		maxTouches: 2,
		textureScaleFactor: 1
		//----auto option end----
    };

    egret.native.NativePlayer.option = option;
    egret.runEgret();
    egret_native.Label.createLabel("/system/fonts/DroidSansFallback.ttf", 20, "", 0);
    egret_native.EGTView.preSetOffScreenBufferEnable(true);
};